import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Types, Document } from 'mongoose';

@Schema()
export class Bid extends Document {
  @Prop({
    type: Types.ObjectId,
    ref: 'User',
    required: true,
  })
  bidder: string; // not in create dto (taken from jwt (req.user))

  @Prop({
    type: Number,
    required: true,
    min: 0,
  })
  bidPrice: number; // in create dto

  @Prop({
    type: Date,
    required: true,
    default: new Date(),
  })
  bidTimestamp?: Date; // not in create dto (autogenerated)
}

export const BidSchema = SchemaFactory.createForClass(Bid);
